
version: '3.8'

services:
  sis_tasksDB:
    image: postgres:15-alpine
    container_name: sis_tasks
    restart: always
    env_file:
      - .env
    volumes:
      - sis_tasks_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    env_file:
      - .env
    ports:
      - "3005:3005"
    depends_on:
      - sis_tasksDB
    networks:
      - backend

volumes:
  sis_tasks_data:

networks:
  backend:
    driver: bridge
